version: '3'
services:
  webapi:
    build:
      context: ./back-end/src/Tryitter
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
      - MSSQL_PID=Developer